export const COLORS = {
  backgroundStart: "#F7F0FA",
  backgroundEnd: "#FFFFFF",
  cardBackground: "rgba(255, 255, 255, 1)",
  bubbleGradientStart: "#FFDEE9",
  bubbleGradientMidStart: "#F0B4CC",
  bubbleGradientMidEnd: "#CB8EED",
  bubbleGradientEnd: "#B081EA",
  cardGradientStart: "#FFFFFF",
  cardGradientEnd: "#FAFAFC",
  textPrimary: "#333333",
  textSecondary: "#817984",
  headerColor: "#8a2be2",
  saveButton: "#ff69b4",
};
